# Dockerfile for Python Client
FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY ./client /app
RUN pip install -r requirements.txt

# Run the Python client (gets server IP and port as arguments)
CMD ["python", "client.py", "server", "8080"]